### ISSUE TITLE
基于EC2搭建TTRSS

### ISSUE THREAD

**Issue by caroundsky** [caroundsky/QA#15]
## 准备工作

* 一个EC2云服务（别的服务也可以）
* 开放EC2端口，与TTRSS指定的一致
* 服务系统中安装好`docker`以及`docker-compose`

Tips：EC2的配置以及`docker`安装可参考 https://github.com/caroundsky/QA/issues/14

## 开放EC2端口

进入亚马逊EC2的管理面板 -> 安全 -> 入站规则 -> 开放181端口 ，我这里开放的是181

![image](https://user-images.githubusercontent.com/20423068/231928054-21544745-6f83-4d33-9755-936814e90d53.png)

## 下载安装TTRSS

1、进入主机，执行以下命令，创建好一个TTRSS目录，并把docker-compose.yml下载到服务器上：
```
#创建 ttrss 目录并进入
mkdir ttrss && cd ttrss

#利用 curl 下载 ttrss 的 docker-compose 配置文件至服务器
curl -fLo docker-compose.yml https://raw.githubusercontent.com/HenryQW/Awesome-TTRSS/main/docker-compose.yml
```

2、进入ttrss目录内，打开并修改配置yml：

![image](https://user-images.githubusercontent.com/20423068/231735334-f855faef-82a4-433d-ac89-f9989225c582.png)

![image](https://user-images.githubusercontent.com/20423068/231736794-37d1769d-649e-41a4-ad04-500d1a309574.png)

其它变量暂未修改，如果有需要，可进入项目文档进行查询配置。

3、安装

执行执行进行安装 `docker-compose up -d` 并确认是否安装成功

![image](https://user-images.githubusercontent.com/20423068/231737645-fb31085d-b129-424a-b3b3-27fd096da18d.png)

4、在浏览器通过域名（未绑定就用ip+端口）访问页面，使用默认账号密码 `admin` 和 `password` 登录并进行一些基本配置。

![image](https://user-images.githubusercontent.com/20423068/231929349-8ad207cb-cf67-4be8-8688-a79b46ad38fc.png)

## 配置使用rsshub主题

* window系统下可能存在问题：

  - 字体文件加载404的问题，可能是主题css内font加载路径与TTRSS内的字体文件路径不一致导致的。
  - 一些样式适配问题

* 字体问题产生原因为主题css指定的字体文件加载路径为 `../lib/iconfont/` ，而TTRSS的字体存放文件位于 `/vendor/mervick/material-design-icons/fonts/`。因此，SSH进入主机，复制一份字体文件到css指定的路径下。

![image](https://user-images.githubusercontent.com/20423068/231930516-edebdaca-b65f-4ca3-a60e-89da555c2d5f.png)

采用以下指令：

1、查询TTRSS在docker运行中的容器id
```
docker ps
```
![image](https://user-images.githubusercontent.com/20423068/231931496-5068b825-7ae4-4863-b425-5699fb3553c1.png)

2、进入容器内，一般使用 `doker exec -it [容器id] /bin/bash`，如果出现类似`"bash": executable file not found in $PATH: unknown`，那么`doker inspect [容器id]` 找出`Cmd`配置，我这边是`null`，那么改为使用`doker exec -it [容器id] sh` 进行登录

![image](https://user-images.githubusercontent.com/20423068/231935709-6d5f471a-4b13-47cc-9bd1-bd81133d7a34.png)

登录后使用以下指令复制文件：
```
cp --path ./vendor/mervick/material-design-icons/fonts/* ./lib/iconfont/
```
复制成功后回到浏览器刷新一下验货。

* 一些样式适配问题通过复制以下css样式进行覆盖即可

![image](https://user-images.githubusercontent.com/20423068/231936813-3e0a8cff-0434-4f64-83fb-e6fcebadf7b6.png)

```css
body.ttrss_main #feeds-holder #feedTree .counterNode.marked {
    display: none;
}

body.ttrss_main #feeds-holder #feedTree .counterNode.aux{
    display: none;
}

body.ttrss_main #feeds-holder #feedTree .dijitTreeRow.AlwaysVisible .counterNode.unread {
    display: none;
}

body.ttrss_main #toolbar-frame #toolbar #toolbar-headlines {
    background: transparent;
}

#feeds-holder#feeds-holder #feedTree .dijitTreeExpandoLeaf {
	top: 3px;
}

#feeds-holder#feeds-holder #feedTree .dijitTreeExpandoLeaf .loadingNode {
    max-width: 100%;	
}

#feeds-holder#feeds-holder #feedTree .counterNode {
	margin-top: 6px;
}

#feeds-holder#feeds-holder #feedTree .dijitTreeExpando {
	left: -5px;
}

body.ttrss_main #main #feeds-holder #feedTree .dijitTreeContentExpanded .loadingNode {
    width: 25px;
    margin: -3px 0 0 5px;
}

body.ttrss_main .dijitSplitter {
    background-color: #eee;
}

#content-wrap#content-wrap [data-article-id].cdm, #content-wrap#content-wrap .hl:first-child {
    border: 0
}

body.ttrss_main #main #feeds-holder #feedTree .dijitTreeNode#dijit__TreeNode_7 .unread {
    display: none
}

body.ttrss_main #headlines-spacer span img {
	width: 40px
}
```

## 拓展
* rsshub主题不自带关闭展示文章区域的按钮，但可以通过安装插件解决。

![image](https://user-images.githubusercontent.com/20423068/231937369-d3b0764c-db00-4872-8e78-9c639f3aaad1.png)

* 订阅相关rss源可参照[rsshub文档](https://docs.rsshub.app/)

* 整体界面效果如下：

![image](https://user-images.githubusercontent.com/20423068/231937595-3aa34fde-7453-433e-8fe1-8c2d58729e1d.png)

## Tips：参考资料
1、https://ttrss.henry.wang/zh/#rsshub
2、https://wzfou.com/ttrss-docker/
3、https://docs.rsshub.app/
